name: Pull Request
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  title:
    name: Ensure that title uses gitmoji
    runs-on: ubuntu-latest
    steps:
      - uses: paralenz/actions/gitmoji@master

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master

  greet:
    name: Greet someone
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
      - run: node myscript.js

