name: Pull Request
on: 
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
      - run: node myscript.js "from the SETUP step"
  
  nodejs:
    name: Set some setOutput
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
      - name: Set some output
        id: nodejs
        run: |
          echo "::set-output name=NODE_VERSION::$(
            cat .tool-versions |
            grep nodejs |
            sed 's/nodejs \(.*\)$/\1/'
          )"

  nodeVersion:
    name: Get the version of node
    runs-on: ubuntu-latest
    needs: [nodejs]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
      - run: echo "Using ${{ steps.nodejs.outputs.NODE_VERSION }} of node"

  greeter:
    name: Greeter
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
      - uses: paralenz/actions/setup-node@master
      - run: node myscript.js "from the GREETER step"

